name: Generate tag version
on:
  workflow_dispatch:
    inputs:
      version:
        description: New version
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  version:
    permissions: write-all
    name: Create new version ${{ github.event.inputs.version }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Generate new version
        run: npm version ${{ github.event.inputs.version }}

      - name: Push new version tag to repository
        with:
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: git push origin main --tags