name: Test React App
on: 
  push:
    branches:
      - main
    paths-ignore:
      - './github/workflows/*'
jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: Get repositiry code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/packadge-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Lint application
        run: npm run lint
  test:
    needs: lint
    runs-on: macos-latest
    steps:
      - name: Get repositiry code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/packadge-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test