name: Test React App
on: push
jobs:
  runs-on: macos-latest
  steps:
    - name: Get repositiry code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Test application
      run: npm run test